# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pre-purchase"
client_id = "e412682a47af4f57f1879e6c6ca0eae9"
application_url = "https://unlike-rehabilitation-temporary-rear.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://unlike-rehabilitation-temporary-rear.trycloudflare.com/auth/callback",
  "https://unlike-rehabilitation-temporary-rear.trycloudflare.com/auth/shopify/callback",
  "https://unlike-rehabilitation-temporary-rear.trycloudflare.com/api/auth/callback",
  "https://unlike-rehabilitation-temporary-rear.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "extension-ui.myshopify.com"
