# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "benifits"
handle = "benifits"

# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
# Gives your extension access to directly query Shopify’s storefront API.
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#api-access
api_access = true

# Gives your extension access to make external network calls, using the
# JavaScript `fetch()` API. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#network-access
# network_access = true

# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# .shopify.yml

# Your other extension configurations

 [extensions.settings]
[[extensions.settings.fields]]
 key = "heading"
 type = "single_line_text_field"
 name = "Banner title"
 description = "Enter a title for the banner"



[[extensions.settings.fields]]
key= "column1Image"
name = "Column 1 Image"
type = "single_line_text_field"
description = "path-to-image-1.jpg"

 [[extensions.settings.fields]]
 key = "column1Text"
 type = "single_line_text_field"
 name = "Column 1 Text"
 description = "Text for Column 1"

 [[extensions.settings.fields]]
key= "column2Image"
name = "Column 2 Image"
type = "single_line_text_field"
description = "path-to-image-2.jpg"

 [[extensions.settings.fields]]
 key = "column2Text"
 type = "single_line_text_field"
 name = "Column 2 Text"
 description = "Text for Column 2"


 [[extensions.settings.fields]]
key= "column3Image"
name = "Column 3 Image"
type = "single_line_text_field"
description = "path-to-image-3.jpg"

 [[extensions.settings.fields]]
 key = "column3Text"
 type = "single_line_text_field"
 name = "Column 3 Text"
 description = "Text for Column 3"


 
